### PR TITLE
Oauth2 auto register

### PR DESCRIPTION
**Pull request by kvaster**
I was a little bit hurry and made stupid bugs.

Fix for lint errors
Fix for validating config options

### CODE REVIEW

**Comment by kvaster** [comment]
My experience with golang is not very big and I'm a little bit confused about custom types for AcoountLinking:

```go
type OAuth2AccountLinkingType string
const (
	OAuth2AccountLinkingDisabled OAuth2AccountLinkingType = "disabled"
	OAuth2AccountLinkingLogin OAuth2AccountLinkingType = "login"
	OAuth2AccountLinkingAuto OAuth2AccountLinkingType = "auto"
)
```

Is there any good way to validate value and fallback to default in case setting is wrong ?

**Comment by mgjm** [comment]
The following should work:
```go
type OAuth2AccountLinkingType string

const (
	OAuth2AccountLinkingDisabled OAuth2AccountLinkingType = "disabled"
	OAuth2AccountLinkingLogin    OAuth2AccountLinkingType = "login"
	OAuth2AccountLinkingAuto     OAuth2AccountLinkingType = "auto"
)

func (accountLinking OAuth2AccountLinkingType) IsValid() bool {
	switch accountLinking {
	case OAuth2AccountLinkingDisabled, OAuth2AccountLinkingLogin, OAuth2AccountLinkingAuto:
		return true
	default:
		return false
	}
}

funk 
```

... and can be used in the following way:
```go
	accountLinking := sec.Key("ACCOUNT_LINKING").MustString(string(OAuth2AccountLinkingDisabled))
	OAuth2Client.AccountLinking = OAuth2AccountLinkingType(accountLinking)
	if !OAuth2Client.AccountLinking.IsValid() {
		log.Warn("Account linking setting is not valid: '%s', will fallback to 'disabled'", OAuth2Client.AccountLinking)
		OAuth2Client.AccountLinking = OAuth2AccountLinkingDisabled
	}
```

**Comment by mgjm** [comment]
Or even moved to a `parse` function:
```go
func (accountLinking *OAuth2AccountLinkingType) parse(key *ini.Key) {
	s := key.MustString(string(OAuth2AccountLinkingDisabled))
	*accountLinking = OAuth2AccountLinkingType(s)
	if !accountLinking.IsValid() {
		log.Warn("Account linking setting is not valid: '%s', will fallback to 'disabled'", *accountLinking)
		*accountLinking = OAuth2AccountLinkingDisabled
	}
}
```

... and used via `OAuth2Client.AccountLinking.parse(sec.Key("ACCOUNT_LINKING"))`

**Comment by kvaster** [comment]
I think that parse function is not needed in this case. Commited fixes for string "enums".

**Pull request merged**
